backend:
  name: git-gateway

local_backend: true

media_folder: static/img
public_folder: /img

site_url: https://katie-frontend.netlify.app

collections:
  - name: 'editor'
    label: 'Editor'
    preview_path: /
    files:
      - label: "Services"
        name: "services"
        file: "content/sections/1-Services.en.md"
        fields:
          - {label: Anchor, name: anchor, widget: string}
          - {label: Header, name: header, widget: string}
          - {label: Subheader, name: subheader, widget: string}
          - label: Services
            name: services
            widget: list
            fields:
              - {label: Header, name: header, widget: string}
              - {label: Content, name: content, widget: string}
              - {label: Icon, name: iconName, widget: string}
      - label: "Gallery"
        name: "gallery"
        file: "content/sections/2-Gallery.en.md"
        fields:
          - {label: Anchor, name: anchor, widget: string}
          - {label: Header, name: header, widget: string}
          - {label: Subheader, name: subheader, widget: string}
          - label: Items
            name: gallery
            widget: list
            fields:
              - {label: Header, name: header, widget: string}
              - {label: Subheader, name: subheader, widget: string}
              - {label: Content, name: content, widget: string}
              - {label: Image, name: imageFileName, widget: image, media_folder: /content/assets/images/gallery}
              - {label: ImageDetail, name: imageFileNameDetail, widget: image, media_folder: /content/assets/images/gallery}
      - label: "Shop"
        name: "shop"
        file: "content/sections/3-Shop.en.md"
        fields:
          - {label: Anchor, name: anchor, widget: string}
          - {label: Header, name: header, widget: string}
          - {label: Subheader, name: subheader, widget: string}
      - label: "Team"
        name: "team"
        file: "content/sections/4-Team.en.md"
        fields:
          - {label: Anchor, name: anchor, widget: string}
          - {label: Header, name: header, widget: string}
          - {label: Subheader, name: subheader, widget: string}
          - {label: Content, name: content, widget: string}
          - label: Members
            name: teamMember
            widget: list
            fields:
              - {label: Name, name: header, widget: string}
              - {label: Job, name: subheader, widget: string}
              - {label: Image, name: imageFileName, widget: image, media_folder: /content/assets/images/team}
              - label: Social
                name: social
                widget: object
                fields:
                  - {label: Instagram, name: instagram, widget: string, required: false}
                  - {label: Facebook, name: facebook, widget: string, required: false}
                  - {label: LinkedIn, name: linkedin, widget: string, required: false}
                  - {label: Github, name: github, widget: string, required: false}
                  - {label: Twitter, name: twitter, widget: string, required: false}
                  - {label: Medium, name: medium, widget: string, required: false}
      - label: "Contact"
        name: "contact"
        file: "content/sections/5-Contact.en.md"
        fields:
          - {label: Anchor, name: anchor, widget: string}
          - {label: Header, name: header, widget: string}
          - {label: Subheader, name: subheader, widget: string}
          - {label: Telephone, name: telephone, widget: string}
          - {label: Email, name: email, widget: string}
    create: false
    media_folder: ''
    public_folder: ''
    editor:
      preview: true