backend:
  name: github
  branch: dev # Branch to update (optional; defaults to master)
  repo: drod917/katie-frontend

media_folder: static/img
public_folder: /img

collections:
  - name: 'services'
    label: 'Services'
    folder: 'content/sections'
    create: false
    slug: '{{header}}'
    media_folder: ''
    public_folder: ''
    path: '1-Services.en'
    editor:
      preview: false
    fields:
      - { label: 'Anchor', name: 'anchor', widget: 'string' }
      - { label: 'Header', name: 'header', widget: 'string' }